package selenium;
// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;

import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import java.util.*;

public class AuthTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        System.setProperty("webdriver.gecko.driver", "/Users/nbiryulin/Downloads/geckodriver");
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test(expected = StaleElementReferenceException.class)
    public void testChromeValid() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        validAuth();
    }

    @Test(expected = StaleElementReferenceException.class)
    public void testFirefoxInvalid() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        validAuth();
    }


    @Test
    public void testChromeInvalidPassword() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        invalidPasAuth();
    }

    @Test
    public void testChromeInvalidLogin() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        invalidLoginAuth();
    }

    @Test
    public void testFirefoxInvalidLogin() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        invalidLoginAuth();
    }

    @Test
    public void testFirefoxValidPassword() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        invalidPasAuth();
    }


    private void validAuth() {
        auth("selenium.testing.itmo", "Tenscores");
        assertNotNull(driver.manage().getCookies());
        WebElement a = driver.findElement(By.xpath("//input[@id=\'passp-field-passwd\']"));
        a.click();
    }

    private void invalidPasAuth() {
        auth("selenium.testing.itmo", "incorrectpas");
        WebElement a = driver.findElement(By.xpath("//input[@id=\'passp-field-passwd\']"));
        a.click();
        WebElement b = driver.findElement(By.xpath("//div[@id=\'root\']/div/div[2]/div[2]/div/div/div[2]"));
        b.click();
        assertEquals("Авторизация", driver.getTitle());
        assertTrue(b.getText().contains("Неверный пароль"));
    }

    private void invalidLoginAuth() {
        authLogin("afeihejasjirsahejkdnhwe");
        WebElement a = driver.findElement(By.xpath("//div[@id='root']/div/div[2]/div[2]/div/div/div[2]/div[3]/div/div/div/div/form/div/div[2]"));
        assertTrue(a.getText().equals("Не помню логин") || a.getText().equals("Такого аккаунта нет"));
    }

    private void auth(String login, String pas) {
        authLogin(login);
        {
            WebElement element = driver.findElement(By.xpath("//button[contains(.,\'Войти\')]"));
            element.click();
        }
        driver.findElement(By.xpath("//div[@id=\'root\']/div/div[2]/div[2]/div/div/div[2]/div[3]/div/div/div/form/div[2]/span/input")).sendKeys(pas);
        driver.findElement(By.xpath("//div[@id=\'root\']/div/div[2]/div[2]/div/div/div[2]/div[3]/div/div/div/form/div[2]/span/input")).click();
        driver.findElement(By.xpath("//button[contains(.,\'Войти\')]")).click();
    }

    private void authLogin(String login) {
        driver.get("http://market.yandex.ru/");
        driver.get("https://passport.yandex.ru/validAuth?retpath=https%3A%2F%2Fmarket.yandex.ru");
        driver.manage().window().setSize(new Dimension(1440, 767));
        vars.put("root", driver.getWindowHandle());
        driver.findElement(By.xpath("//input[@id=\'passp-field-login\']")).sendKeys(login);
        driver.findElement(By.xpath("//div[@id=\'root\']/div/div[2]")).click();
        driver.findElement(By.xpath("//button[contains(.,\'Войти\')]")).click();
    }
}
