package selenium;
// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;

import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.*;

public class AuthTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        System.setProperty("webdriver.gecko.driver","/Users/nbiryulin/Downloads/geckodriver");
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void testChrome() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        auth();
    }

    @Test
    public void testFirefox() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        auth();
    }



    public void auth() {
        driver.get("http://market.yandex.ru/");
        // Test name: auth
        // Step # | name | target | value | comment
        // 1 | open | https://passport.yandex.ru/auth?retpath=https%3A%2F%2Fmarket.yandex.ru%2Fcloser.html%3Fsocial-broker_seed%3D1606657487282202a9e%23status%3Dok&retnopopup=&consumer=market&action_if_anonymous=ignore&result_location=fragment&provider=ya&sid=25&display=popup&origin=market_desktop_header |  |
        driver.get("https://passport.yandex.ru/auth?retpath=https%3A%2F%2Fmarket.yandex.ru");
        // 2 | setWindowSize | 1440x767 |  |
        driver.manage().window().setSize(new Dimension(1440, 767));
        // 3 | storeWindowHandle | root |  |
        vars.put("root", driver.getWindowHandle());
        driver.findElement(By.xpath("//input[@id=\'passp-field-login\']")).sendKeys("selenium.testing.itmo");
        driver.findElement(By.xpath("//div[@id=\'root\']/div/div[2]")).click();
        // 7 | click | xpath=//form[@action='https://passport.yandex.ru/auth?origin=market_desktop_header&retpath=https%3A%2F%2Fmarket.yandex.ru%2Fcloser.html%3Fsocial-broker_seed%3D1606657487282202a9e%23status%3Dok'] |  |
        //   driver.findElement(By.xpath("//form[@action=\'https://passport.yandex.ru/auth?origin=market_desktop_header&retpath=https%3A%2F%2Fmarket.yandex.ru\']")).click();
        // 8 | click | xpath=//button[contains(.,'Войти')] |  |
        driver.findElement(By.xpath("//button[contains(.,\'Войти\')]")).click();
        // 9 | mouseOver | xpath=//button[contains(.,'Войти')] |  |
        {
            WebElement element = driver.findElement(By.xpath("//button[contains(.,\'Войти\')]"));
            element.click();
        }
        // 10 | type | xpath=//div[@id='root']/div/div[2]/div[2]/div/div/div[2]/div[3]/div/div/div/form/div[2]/span/input | Hekut123 |
        driver.findElement(By.xpath("//div[@id=\'root\']/div/div[2]/div[2]/div/div/div[2]/div[3]/div/div/div/form/div[2]/span/input")).sendKeys("Tenscores");
        // 11 | click | xpath=//div[@id='root']/div/div[2]/div[2]/div/div/div[2]/div[3]/div/div/div/form/div[2]/span/input |  |
        driver.findElement(By.xpath("//div[@id=\'root\']/div/div[2]/div[2]/div/div/div[2]/div[3]/div/div/div/form/div[2]/span/input")).click();
        // 12 | click | xpath=//button[contains(.,'Войти')] |  |
        driver.findElement(By.xpath("//button[contains(.,\'Войти\')]")).click();
        assertNotNull(driver.manage().getCookies());
    }
}
