package selenium;// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;

import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class BonusesTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        System.setProperty("webdriver.gecko.driver","/Users/nbiryulin/Downloads/geckodriver");
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void test() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        bonuses();
        driver.quit();
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        bonuses();
    }


    public void bonuses() {
        driver.get("https://market.yandex.ru/");
        driver.manage().window().setSize(new Dimension(1440, 877));
        driver.findElement(By.xpath("//a/span/div")).click();
        js.executeScript("window.scrollTo(0,638)");
        assertTrue(driver.getCurrentUrl().contains("bonus"));
    }
}
