package selenium;// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;


import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;


import java.util.*;


public class ItemToFavoritesTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        System.setProperty("webdriver.gecko.driver", "/Users/nbiryulin/Downloads/geckodriver");
    }

    @After
    public void tearDown() {
        driver.quit();
    }


    @Test(expected = ElementClickInterceptedException.class)
    public void testChrome() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        itemToFavorites();
    }

    @Test(expected = ElementClickInterceptedException.class)
    public void testFirefox() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        itemToFavorites();
    }


    public void itemToFavorites() {
        driver.get("https://market.yandex.ru/");
        driver.manage().window().setSize(new Dimension(1440, 877));
        driver.findElement(By.xpath("//a/div/div/picture/img")).click();
        driver.findElement(By.xpath("//div[2]/div/div/div/span[2]")).click();
        driver.findElement(By.cssSelector(".b_3ioN70chUh:nth-child(3) svg")).click();
    }
}
