package selenium;// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.*;

public class ItemToCartTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        System.setProperty("webdriver.gecko.driver", "/Users/nbiryulin/Downloads/geckodriver");
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void testChromeNA() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        notAuthorized();
    }

    @Test
    public void testFirefoxNA() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        notAuthorized();
    }

    private void notAuthorized() {
        driver.manage().deleteAllCookies();
        driver.get("https://market.yandex.ru/");
        driver.manage().window().setSize(new Dimension(1440, 877));
        driver.findElement(By.xpath("//a/div/div/picture/img")).click();
        driver.findElement(By.xpath("//span[contains(.,'Добавить в корзину')]")).click();
        js.executeScript("window.scrollTo(0,315)");
        driver.findElement(By.xpath("//a/button/span")).click();
        assertEquals("Авторизация", driver.getTitle());
    }
}
