package selenium;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
public class ListOfTranslationsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.gecko.driver", "/Users/nbiryulin/Downloads/geckodriver");
  }
  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
 public void testChrome() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    listOfTranslations();
  }

  @Test
  public void testFirefox() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    listOfTranslations();
  }

  public void listOfTranslations() {
    driver.get("https://market.yandex.ru/");
    driver.manage().window().setSize(new Dimension(1440, 877));
    driver.findElement(By.xpath("//div[2]/div/div[2]/div/div/div/div/div/a/span")).click();
    assertTrue(driver.getCurrentUrl().contains("live"));
  }
}
