package selenium;// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class RegionTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        System.setProperty("webdriver.gecko.driver", "/Users/nbiryulin/Downloads/geckodriver");
    }

    @Test
    public void test() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        aSd();
        driver.quit();
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        aSd();
        driver.quit();
    }

    @After
    public void quit() {
        driver.quit();
    }


    public void aSd() {
        driver.get("https://market.yandex.ru/bonus?track=head");
        driver.manage().window().setSize(new Dimension(1200, 746));
        driver.findElement(By.xpath("//button/div[2]")).click();
        driver.findElement(By.xpath("//div[3]/button/span")).click();
        WebElement a = driver.findElement(By.xpath("//button/div[2]"));
        assertEquals("Санкт-Петербург", a.getText());
    }
}
